language: cpp
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - +ACIAJA-HOME/.ccache+ACI-
addons:
  apt:
    sources:
    - ppa:bitcoin/bitcoin
    packages:
    - autoconf
    - autotools-dev
    - binutils
    - bsdmainutils
    - build-essential
    - cmake
    - curl
    - libboost-all-dev
    - libbz2-dev
    - libcap-dev
    - libdb4.8-dev
    - libdb4.8dev
    - libevent-dev
    - libssl-dev
    - libtool
    - linux-libc-dev
    - miniupnpc
    - pkg-config
    - python-dev
    - python-setuptools
    - python3
    - python3-zmq
    - zlib1g-dev
env:
  global:
  - FANTASYGOLD+AF8-VERSION+AD0-2.0.0.0
  - CCACHE+AF8-COMPRESS+AD0-1
  - CCACHE+AF8-SIZE+AD0-500M
  - CCACHE+AF8-TEMPDIR+AD0-/tmp/.ccache-temp
  - MAKEJOBS+AD0AIg--s -j 2+ACI-
matrix:
  include:
  - name: Linux ARM 32 Bit
    addons:
      apt:
        packages:
        - garm-linux-gnueabihf
        - binutils-arm-linux-gnueabihf
    env:
    - FANTASYGOLD+AF8-CONFIG+AD0AIg---enable-glibc-back-compat --with-gui+AD0-no+ACI-
    - HOST+AD0-arm-linux-gnueabihf
    - LABEL+AD0-ARM
    os: linux
  - name: Linux i686 32 Bit
    addons:
      apt:
        packages:
        - bc
        - gmultilib
        - libprotobuf-dev
        - libqrencode-dev
        - python3-zmq
        - qtdeclarative5-dev
    env:
    - FANTASYGOLD+AF8-CONFIG+AD0AIg---enable-zmq --enable-glibc-back-compat LDFLAGS+AD0--static-libstdc
      --with-gui+AD0-qt5+ACI-
    - HOST+AD0-i686-pc-linux-gnu
    - LABEL+AD0-linux32
    - PYZMQ+AD0-true
    os: linux
  - name: Linux x86 64 Bit
    addons:
      apt:
        packages:
        - bc
        - libprotobuf-dev
        - libqrencode-dev
        - python3-zmq
        - qtdeclarative5-dev
    env:
    - FANTASYGOLD+AF8-CONFIG+AD0AIg---enable-zmq --enable-glibc-back-compat LDFLAGS+AD0--static-libstdc
      --with-gui+AD0-qt5+ACI-
    - CPPFLAGS+AD0AIg--DDEBUG+AF8-LOCKORDER -DENABLE+AF8-DASH+AF8-DEBUG+ACI-
    - HOST+AD0-x86+AF8-64-pc-linux-gnu
    - LABEL+AD0-linux64
    - PYZMQ+AD0-true
    os: linux
  - name: Windows i686 32 Bit
    addons:
      apt:
        packages:
        - gmingw-w64-i686 bc
        - libprotobuf-dev
        - libqrencode-dev
        - linux-libc-dev:i386
        - nsis
        - python3
        - qtdeclarative5-dev
    env:
    - FANTASYGOLD+AF8-CONFIG+AD0AIg---with-gui+AD0-qt5+ACI-
    - HOST+AD0-i686-w64-mingw32
    - LABEL+AD0-win32
    os: linux
  - name: Windows x86 64 Bit
    addons:
      apt:
        packages:
        - bc
        - gmingw-w64-x86-64
        - libprotobuf-dev
        - libqrencode-dev
        - linux-libc-dev:i386
        - nsis
        - python3
        - qtdeclarative5-dev
    env:
    - FANTASYGOLD+AF8-CONFIG+AD0AIg---with-gui+AD0-qt5+ACI-
    - HOST+AD0-x86+AF8-64-w64-mingw32
    - LABEL+AD0-win64
    os: linux
  - name: macOS x86 64 Bit
    env:
    - HOST+AD0-x86+AF8-64-apple-darwin
    - LABEL+AD0-macOS
    os: osx
    osx+AF8-image: xcode9.2
before+AF8-install:
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-osx+ACI- +AF0AXQA7- then brew update+ADs- fi
install:
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-osx+ACI- +AF0AXQA7- then brew uninstall mercurial python+ADs- brew
  bundle+ADs- brew link --overwrite --force boost+AEA-1.57+ADs- fi
- if +AFs- +ACIAJA-PYZMQ+ACI- +AD0- +ACI-true+ACI- +AF0AOw- then pip install pyzmq --user +ADs- fi
before+AF8-script:
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-linux+ACI- +AF0AXQA7- then unset CC CXX DISPLAY+ADs- fi
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-osx+ACI- +AF0AXQA7- then export LDFLAGS+AD0--L/usr/local/opt/openssl/lib+ADs-
  export CPPFLAGS+AD0--I/usr/local/opt/openssl/include+ADs- fi
- GLOBAL+AF8-CONFIG+AD0AIg---enable-reduce-exports --enable-tests --prefix+AD0AJA-TRAVIS+AF8-BUILD+AF8-DIR/depends/+ACQ-HOST+ACI-
script:
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-linux+ACI- +AF0AXQA7- then make +ACQ-MAKEJOBS -C depends HOST+AD0AIgAk-HOST+ACIAOw-
  depends/+ACQ-HOST/native/bin/ccache --max-size+AD0AJA-CCACHE+AF8-SIZE+ADs- sh ./autogen.sh+ADs- ./configure
  --cache-file+AD0-config.cache +ACQ-GLOBAL+AF8-CONFIG +ACQ-FANTASYGOLD+AF8-CONFIG+ADs- make+ADs- fi
- if +AFsAWw- +ACIAJA-TRAVIS+AF8-OS+AF8-NAME+ACI- +AD0APQ- +ACI-osx+ACI- +AF0AXQA7- then sh ./autogen.sh+ADs- ./configure --enable-reduce-exports+ADs-
  make deploy+ADs- fi
before+AF8-deploy:
- true
